name: GitHub Actions CI for push

on:
  workflow_dispatch:
    
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - release/*
  push:
    branches:
      - main
      - feature/*
env:
  GO_VERSION: '1.23'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: false
      - name: run build
        run: |-
          pwd
          make build-prod


